name: "build and package"
on:
  push:
    branches:
      - main # 指定分支名称,可以是 master、develop 等

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: install dependencies
      run: |
        export ELECTRON_SKIP_BINARY_DOWNLOAD=1
        npm install

    - name: build
      run: npm run build

    - name: package
      run: |
        sudo apt install zip -y
        cp manifest.json ./dist/manifest.json
        cd ./dist/
        zip -r ../LLOneBot.zip ./*

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: LLOneBot
        path: LLOneBot.zip
